<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0-android</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net10.0-android'">21</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Slither.Core\Slither.Core.csproj" />
    <ProjectReference Include="..\Slither.Protocol\Slither.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\BackGround.jpg"
                      LogicalName="Slither.Client.Assets.background.jpg" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.5.1" />
  </ItemGroup>

</Project>
